[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF019510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dea2969a634182552b2a04b5c416cac6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF019630>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dea2969a634182552b2a04b5c416cac6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF0197B0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/dea2969a634182552b2a04b5c416cac6
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF01A6E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b09fbe361691725df2fb6297ed2df47a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF01A7A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b09fbe361691725df2fb6297ed2df47a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF01A920>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/b09fbe361691725df2fb6297ed2df47a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF115450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a358e65cdd044224c5b94df117be44f9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF115510>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a358e65cdd044224c5b94df117be44f9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF115690>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a358e65cdd044224c5b94df117be44f9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF148DF0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2152a750258d1630b023595d65ad34df
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF14AA40>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2152a750258d1630b023595d65ad34df
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020DCF1498A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/2152a750258d1630b023595d65ad34df