[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC49D2C50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ebe22746f9590843612cbf5bbee116ce
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC49D2410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ebe22746f9590843612cbf5bbee116ce
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC49D3250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/ebe22746f9590843612cbf5bbee116ce
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4A8A560>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14398b4ddfedc7c201d8b48c078aedf8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4A8AD70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14398b4ddfedc7c201d8b48c078aedf8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4A8B0D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/14398b4ddfedc7c201d8b48c078aedf8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4AB4250>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/86ccfa7d873b364694230f2b0cfbc69d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4AB4040>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/86ccfa7d873b364694230f2b0cfbc69d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4AB4730>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/86ccfa7d873b364694230f2b0cfbc69d
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4ACC190>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a992288ee0411ba9be980eff308d0674
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4ACC280>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a992288ee0411ba9be980eff308d0674
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000022BC4ACC6A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/a992288ee0411ba9be980eff308d0674