[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001652CAFE230>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03280ee35309a0d45e4dff4a2f651fb9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001652C9772E0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03280ee35309a0d45e4dff4a2f651fb9
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001652CAB24A0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/03280ee35309a0d45e4dff4a2f651fb9